### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Elsfa7-110** [h0tak88r/subMonit88r#1]
go install github.com/cyinnove/subfalcon/cmd/subfalcon@latest

go: github.com/cyinnove/subfalcon/cmd/subfalcon@latest: version constraints conflict:
        github.com/cyinnove/subfalcon@v1.0.1: parsing go.mod:
        module declares its path as: github.com/h0tak88r/subfalcon
                but was required as: github.com/cyinnove/subfalcon

**Comment by h0tak88r** [comment]
Hi @Elsfa7-110,
The issue should be resolved now and i have added some features like working with one domain and now have pushed V2 !!
the changes should reflect in the upcomming 30 mins
Have a good day 
![image](https://github.com/user-attachments/assets/f28b0f9c-8063-4c95-9e3c-1232ee7810b6)
